services:
  ldap-nel:
    image: dethdkn/ldap-nel:latest
    volumes:
      - ./database:/database
    ports:
      - 3000:3000
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    restart: unless-stopped
